version: '3'

services:

  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./htdocs:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - backend

  php-fpm:
    build:
      context: ./php
    volumes:
      - ./htdocs:/var/www/html
    expose:
      - '9000'
    networks:
      - backend

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - ./mysql/lib/mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
